# File autogenerated from Ensembl REST API. Do not edit.
#
# Manually edited.
#
# Data source:
# https://www.ncbi.nlm.nih.gov/genome/?term=txid69293%5BOrganism:noexp%5D
# In the table under the 'Representative' tab,  in the RefSeq column,
# I took only the lengths of chromosomes that started with NC_053*

data = {
    "assembly_accession": None,
    "assembly_name": "BROAD S1",
    "chromosomes": {
        "1": {"length": 29620000, "synonyms": []},
        "2": {"length": 23690000, "synonyms": []},
        "3": {"length": 17760000, "synonyms": []},
        "4": {"length": 34180000, "synonyms": []},
        "5": {"length": 15550000, "synonyms": []},
        "6": {"length": 18830000, "synonyms": []},
        "7": {"length": 30780000, "synonyms": []},
        "8": {"length": 20550000, "synonyms": []},
        "9": {"length": 20840000, "synonyms": []},
        "10": {"length": 17990000, "synonyms": []},
        "11": {"length": 17650000, "synonyms": []},
        "12": {"length": 20690000, "synonyms": []},
        "13": {"length": 20750000, "synonyms": []},
        "14": {"length": 16150000, "synonyms": []},
        "15": {"length": 17320000, "synonyms": []},
        "16": {"length": 19510000, "synonyms": []},
        "17": {"length": 20200000, "synonyms": []},
        "18": {"length": 15940000, "synonyms": []},
        "19": {"length": 20580000, "synonyms": []},
        "20": {"length": 20450000, "synonyms": []},
        "21": {"length": 17420000, "synonyms": []},
        "Y": {"length": 15860000, "synonyms": []},
    },
}
