queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-deploy-docs
      - check-success=pre-commit
      - check-success=tests (ubuntu-18.04, 3.7)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (macos-10.15, 3.7)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (windows-latest, 3.7)
      - check-success=tests (windows-latest, 3.10)
      - check-success=codecov/patch
      - check-success=codecov/project

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=build-deploy-docs
      - check-success=pre-commit
      - check-success=tests (ubuntu-18.04, 3.7)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (macos-10.15, 3.7)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (windows-latest, 3.7)
      - check-success=tests (windows-latest, 3.10)
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      queue:
        name: default
