# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000090745.1",
    "assembly_name": "AnoCar2.0",
    "chromosomes": {
        "1": {"length": 263920458, "synonyms": []},
        "2": {"length": 199619895, "synonyms": []},
        "3": {"length": 204416410, "synonyms": []},
        "4": {"length": 156502444, "synonyms": []},
        "5": {"length": 150641573, "synonyms": []},
        "6": {"length": 80741955, "synonyms": []},
        "LGa": {"length": 7025928, "synonyms": []},
        "LGb": {"length": 3271537, "synonyms": []},
        "LGc": {"length": 9478905, "synonyms": []},
        "LGd": {"length": 1094478, "synonyms": []},
        "LGf": {"length": 4257874, "synonyms": []},
        "LGg": {"length": 424765, "synonyms": []},
        "LGh": {"length": 248369, "synonyms": []},
        "MT": {"length": 17223, "synonyms": []},
    },
}
