# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000090745.2",
    "assembly_name": "AnoCar2.0v2",
    "chromosomes": {
        "1": {"length": 263920458, "synonyms": ["chr1"]},
        "2": {"length": 199619895, "synonyms": ["chr2"]},
        "3": {"length": 204416410, "synonyms": ["chr3"]},
        "4": {"length": 156502444, "synonyms": ["chr4"]},
        "5": {"length": 150641573, "synonyms": ["chr5"]},
        "6": {"length": 80741955, "synonyms": ["chr6"]},
        "a": {"length": 7025928, "synonyms": ["chrLGa"]},
        "b": {"length": 3271537, "synonyms": ["chrLGb"]},
        "c": {"length": 9478905, "synonyms": ["chrLGc"]},
        "d": {"length": 1094478, "synonyms": ["chrLGd"]},
        "f": {"length": 4257874, "synonyms": ["chrLGf"]},
        "g": {"length": 424765, "synonyms": ["chrLGg"]},
        "h": {"length": 248369, "synonyms": ["chrLGh"]},
    },
}
