# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000005575.1",
    "assembly_name": "AgamP4",
    "chromosomes": {
        "2L": {"length": 49364325, "synonyms": []},
        "2R": {"length": 61545105, "synonyms": []},
        "3L": {"length": 41963435, "synonyms": []},
        "3R": {"length": 53200684, "synonyms": []},
        "X": {"length": 24393108, "synonyms": []},
        "Mt": {"length": 15363, "synonyms": []},
    },
}
