# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: requirements/conda-minimal.txt

python:
  # Install the local package using pip so that stdpopsim is in the path.
  install:
    - method: pip
      path: .
