# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000001735.1",
    "assembly_name": "TAIR10",
    "chromosomes": {
        "1": {"length": 30427671, "synonyms": []},
        "2": {"length": 19698289, "synonyms": []},
        "3": {"length": 23459830, "synonyms": []},
        "4": {"length": 18585056, "synonyms": []},
        "5": {"length": 26975502, "synonyms": []},
        "Mt": {"length": 366924, "synonyms": []},
        "Pt": {"length": 154478, "synonyms": []},
    },
    "assembly_source": "ensembl",
    "assembly_build_version": "113",
}
