# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000689235.1",
    "assembly_name": "GBCO_p1",
    "chromosomes": {"1": {"length": 2065074, "synonyms": ["I"]}},
    "assembly_source": "ensembl",
    "assembly_build_version": "103",
}
