# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000309985.1",
    "assembly_name": "Brapa_1.0",
    "chromosomes": {
        "A01": {"length": 28605136, "synonyms": []},
        "A02": {"length": 27846329, "synonyms": []},
        "A03": {"length": 31715688, "synonyms": []},
        "A04": {"length": 18965343, "synonyms": []},
        "A05": {"length": 23939834, "synonyms": []},
        "A06": {"length": 26271742, "synonyms": []},
        "A07": {"length": 22586724, "synonyms": []},
        "A08": {"length": 21594650, "synonyms": []},
        "A09": {"length": 37120481, "synonyms": []},
        "A10": {"length": 17594535, "synonyms": []},
    },
}
