# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000001215.4",
    "assembly_name": "BDGP6.46",
    "chromosomes": {
        "2L": {"length": 23513712, "synonyms": []},
        "2R": {"length": 25286936, "synonyms": []},
        "3L": {"length": 28110227, "synonyms": []},
        "3R": {"length": 32079331, "synonyms": []},
        "4": {"length": 1348131, "synonyms": []},
        "X": {"length": 23542271, "synonyms": []},
        "Y": {"length": 3667352, "synonyms": []},
        "mitochondrion_genome": {"length": 19524, "synonyms": []},
    },
    "assembly_source": "ensembl",
    "assembly_build_version": "113",
}
