# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000967155.1",
    "assembly_name": "HUSEC2011CHR1",
    "chromosomes": {"Chromosome": {"length": 5277676, "synonyms": []}},
}
