# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_002127325.2",
    "assembly_name": "HanXRQr2.0-SUNRISE",
    "chromosomes": {
        "1": {"length": 149502186, "synonyms": []},
        "2": {"length": 174800439, "synonyms": []},
        "3": {"length": 176490873, "synonyms": []},
        "4": {"length": 208320189, "synonyms": []},
        "5": {"length": 178169690, "synonyms": []},
        "6": {"length": 148147350, "synonyms": []},
        "7": {"length": 149542083, "synonyms": []},
        "8": {"length": 167167940, "synonyms": []},
        "9": {"length": 189665024, "synonyms": []},
        "10": {"length": 181411567, "synonyms": []},
        "11": {"length": 189830405, "synonyms": []},
        "12": {"length": 163781230, "synonyms": []},
        "13": {"length": 173487274, "synonyms": []},
        "14": {"length": 173346949, "synonyms": []},
        "15": {"length": 175671323, "synonyms": []},
        "16": {"length": 206736614, "synonyms": []},
        "17": {"length": 195042445, "synonyms": []},
    },
}
