# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_002204515.1",
    "assembly_name": "AaegL5",
    "chromosomes": {
        "1": {"length": 310827022, "synonyms": []},
        "2": {"length": 474425716, "synonyms": []},
        "3": {"length": 409777670, "synonyms": []},
        "MT": {"length": 16790, "synonyms": []},
    },
    "assembly_source": "ensembl",
    "assembly_build_version": "113",
}
