# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_001433935.1",
    "assembly_name": "IRGSP-1.0",
    "chromosomes": {
        "1": {"length": 43270923, "synonyms": []},
        "Mt": {"length": 490520, "synonyms": []},
        "Pt": {"length": 134525, "synonyms": []},
        "2": {"length": 35937250, "synonyms": []},
        "3": {"length": 36413819, "synonyms": []},
        "4": {"length": 35502694, "synonyms": []},
        "5": {"length": 29958434, "synonyms": []},
        "6": {"length": 31248787, "synonyms": []},
        "7": {"length": 29697621, "synonyms": []},
        "8": {"length": 28443022, "synonyms": []},
        "9": {"length": 23012720, "synonyms": []},
        "10": {"length": 23207287, "synonyms": []},
        "11": {"length": 29021106, "synonyms": []},
        "12": {"length": 27531856, "synonyms": []},
    },
    "assembly_source": "ensembl",
    "assembly_build_version": "113",
}
