# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000002595.3",
    "assembly_name": "Chlamydomonas_reinhardtii_v5.5",
    "chromosomes": {
        "1": {"length": 8033585, "synonyms": []},
        "2": {"length": 9223677, "synonyms": []},
        "3": {"length": 9219486, "synonyms": []},
        "4": {"length": 4091191, "synonyms": []},
        "5": {"length": 3500558, "synonyms": []},
        "6": {"length": 9023763, "synonyms": []},
        "7": {"length": 6421821, "synonyms": []},
        "8": {"length": 5033832, "synonyms": []},
        "9": {"length": 7956127, "synonyms": []},
        "10": {"length": 6576019, "synonyms": []},
        "11": {"length": 3826814, "synonyms": []},
        "12": {"length": 9730733, "synonyms": []},
        "13": {"length": 5206065, "synonyms": []},
        "14": {"length": 4157777, "synonyms": []},
        "15": {"length": 1922860, "synonyms": []},
        "16": {"length": 7783580, "synonyms": []},
        "17": {"length": 7188315, "synonyms": []},
    },
}
