# File autogenerated from Ensembl REST API. Do not edit.
#
# Manually edited. See
# https://github.com/popsim-consortium/stdpopsim/issues/835#issuecomment-815854055
#
# Data source:
# http://ensembl.lepbase.org/Heliconius_melpomene_melpomene_hmel25/Info/Index
#
data = {
    "assembly_accession": None,  # No accession number available
    "assembly_name": "Hmel2.5",
    "chromosomes": {
        "1": {"length": 17206585, "synonyms": []},
        "2": {"length": 9045316, "synonyms": []},
        "3": {"length": 10541528, "synonyms": []},
        "4": {"length": 9662098, "synonyms": []},
        "5": {"length": 9908586, "synonyms": []},
        "6": {"length": 1405417, "synonyms": []},
        "7": {"length": 1430885, "synonyms": []},
        "8": {"length": 9320449, "synonyms": []},
        "9": {"length": 8708747, "synonyms": []},
        "10": {"length": 1796548, "synonyms": []},
        "11": {"length": 1175927, "synonyms": []},
        "12": {"length": 1632729, "synonyms": []},
        "13": {"length": 1812731, "synonyms": []},
        "14": {"length": 9174305, "synonyms": []},
        "15": {"length": 1023575, "synonyms": []},
        "16": {"length": 1008321, "synonyms": []},
        "17": {"length": 1477329, "synonyms": []},
        "18": {"length": 1680389, "synonyms": []},
        "19": {"length": 1639934, "synonyms": []},
        "20": {"length": 1487169, "synonyms": []},
        "21": {"length": 1335969, "synonyms": []},
    },
}
