# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000002985.3",
    "assembly_name": "WBcel235",
    "chromosomes": {
        "I": {"length": 15072434, "synonyms": []},
        "II": {"length": 15279421, "synonyms": []},
        "III": {"length": 13783801, "synonyms": []},
        "IV": {"length": 17493829, "synonyms": []},
        "V": {"length": 20924180, "synonyms": []},
        "X": {"length": 17718942, "synonyms": []},
        "MtDNA": {"length": 13794, "synonyms": []},
    },
    "assembly_source": "ensembl",
    "assembly_build_version": "113",
}
