name: pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install lint deps
        run: uv sync --locked --only-group lint

      - name: Cache pre-commit hook environments
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run --locked --only-group lint pre-commit run --all-files --show-diff-on-failure
