name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        python: ["3.11", "3.14"]
    env:
      CONDA_ENV_NAME: stdpopsim
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: Cache conda and dependencies
        id: cache
        uses: actions/cache@v4.2.0
        env:
          # Increase this to reset the cache if the key hasn't changed.
          CACHE_NUM: 1
        with:
          path: ${{ env.CONDA }}/envs
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.python}}-conda-${{ env.CACHE_NUM }}-${{ hashFiles('requirements/CI/*') }}

      - name: Install Conda
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: anaconda-client-env
          init-shell: bash
          create-args: |
            python=${{ matrix.python }}

      - name: Fix windows .profile
        if: steps.cache.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        run: |
          cp ~/.bash_profile ~/.profile

      - name: Install conda deps
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash -l {0} #We need a login shell to get conda
        run: |
          micromamba install --yes --file=requirements/CI/conda.txt

      - name: Install pip deps
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
            pip install -r requirements/CI/requirements.txt

      - name: Install development SLiM
      # This should be COMMENTED OUT for release versions,
      # since this builds SLiM from github head.
        if: (matrix.os == 'macos-latest' || matrix.os == 'ubuntu-24.04') && steps.cache.outputs.cache-hit != 'true'
        # If we want to re-build slim from a new commit to the slim repo
        # we may need to bump the cache key above.
        shell: bash -l {0}
        run: |
          git clone https://github.com/messerlab/SLiM.git
          mkdir -p SLiM/Release
          cd SLiM/Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j 2

      - name: run test suite
        shell: bash -l {0}
        run: |
          micromamba activate anaconda-client-env
          export PATH=$PWD/SLiM/Release:$PATH
          slim -v
          python -m pytest \
            -n 0 \
            -v \
            --cov=stdpopsim \
            --cov-branch \
            --cov-report=term-missing \
            --cov-report=xml \
            tests

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v5.1.1
        with:
          fail_ci_if_error: true
          env_vars: OS,PYTHON
          # Use upload token to avoid upload failures.
          # https://github.com/codecov/codecov-action/issues/837
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
